[Setting]
spotify_path           = C:\Users\48796\AppData\Roaming\Spotify
prefs_path             = C:\Users\48796\AppData\Roaming\Spotify\prefs
current_theme          = DynamicGlow
color_scheme           = Dark-Base
overwrite_assets       = 0
check_spicetify_update = 1
inject_theme_js        = 1
inject_css             = 1
replace_colors         = 1
spotify_launch_flags   = 
always_enable_devtools = 1

[Preprocesses]
expose_apis        = 1
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1

[AdditionalOptions]
extensions            = Vibrant.min.js|dynamicglow-features.js|default-dynamic.js|progress-bar-glow.js|innovative-effects.js|force-bloom.js|listPlaylistsWithSong.js|dom-inspector.js|enhanced-effects.js|dynamic-glow-config.js|live-wrapped.js|super-spotify-8910.js
custom_apps           = Lyrixed|spicetify-history|marketplace|genius-annotations|history-in-sidebar|Enhancify
sidebar_config        = 0
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.84.476.ga1ff6607
with    = 2.42.14
